name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Gateway service
        uses: docker/build-push-action@v4
        with:
          context: ./services/gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-gateway:latest

      - name: Build and push Menu service
        uses: docker/build-push-action@v4
        with:
          context: ./services/menu
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-menu:latest

      - name: Build and push Order service
        uses: docker/build-push-action@v4
        with:
          context: ./services/order
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-order:latest

      - name: Build and push Inventory service
        uses: docker/build-push-action@v4
        with:
          context: ./services/inventory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-inventory:latest

      - name: Build and push Customer service
        uses: docker/build-push-action@v4
        with:
          context: ./services/customer
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-customer:latest

      - name: Build and push Payment service
        uses: docker/build-push-action@v4
        with:
          context: ./services/payment
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cafe-payment:latest 